---
title: "C Berry | Research"
output:
  html_document:
    css: 'style.css'
---


<br>

##### Research Areas

My research is primarily concerned with furthering our understanding of human memory, and using formal models to achieve this. A complete understanding how memory works will ultimately have implications for how we treat memory impairments (e.g., in ageing or amnesia), and also for maximising everyday cognitive function. Formal models are a means of implementing and testing competing theories in a rigorous and transparent manner. My specific areas of investigation are: implicit (unconscious) memory; the role of attention in memory; signal detection theory; the relation between repetition priming, recognition memory, fluency, and source memory; mathematical modelling; everyday amnesia.



<br>

##### Research links

- [Google Scholar](https://scholar.google.co.uk/citations?user=AJV57-4AAAAJ&hl=en)
- [Orcid](https://orcid.org/0000-0002-3512-3604)
- [University of Plymouth pages](https://www.plymouth.ac.uk/staff/christopher-berry)


<br>

##### Grants & Contracts

ESRC Research Grant (2016 - 2020). Modelling explicit and implicit memory: linking priming, recognition, and source memory. Principal Investigator, £264,974.

ESRC Research Fellowship (Dec 2007 - Jan 2011). Testing formal single- and dual-system models of recognition, priming and fluency. Principal Investigator, £226,607. (Fellowship mentor: Prof. D. Shanks; Collaborator: Prof R. Henson.)

Wellcome Trust Value in People Award (Jan 2011 - April 2011). £5,106.
