---
title: "C Berry | Teaching"
output:
  html_document:
    css: 'style.css'
---


<br>

##### Teaching

Main areas: memory, research methods, and statistics.


Undergraduate

- Cognitive Psychology (PSYC421, Module Leader)

- Current Topics in Psychology A (PSYC602)



Postgraduate

- Advanced Psychology Research Project (PSYC722) (Module Leader)


I am also an undergraduate and master's tutorial leader and supervise BSc and MSc dissertation projects. 

<br>


##### Award Nominations

2022    Nominated for the award of Creative Teacher of the Year, SSTAR Awards, University of Plymouth.

2021     Nominated for the award of Outstanding Personal Tutor, SSTAR Awards, University of Plymouth.

2020     Twice nominated for the award of Most Dedicated Dissertation Supervisor SSTAR Awards, University of Plymouth.

2019     Highly commended for the award of Best Placement Support, SSTAR Awards, University of Plymouth.

2019     Nominated twice for the award of Outstanding Personal Tutor, SSTAR Awards, University of Plymouth.

2019     Nominated for the award of Most Dedicated Dissertation Supervisor SSTAR Awards, University of Plymouth.

2018     Nominated twice for the award of Outstanding Personal Tutor, SSTAR Awards, University of Plymouth.

2018     Nominated for the award of Most Dedicated Dissertation Supervisor SSTAR Awards, University of Plymouth.

2016     Nominated for the award of Inspirational Teaching, SSTAR Awards, University of Plymouth.

2016     Nominated for the award of Outstanding Personal Tutor, SSTAR Awards, University of Plymouth.

2014     Nominated for the Postgraduate Certificate in Academic Practice Award of Excellence, University of Plymouth.